# Generated by Django 2.2.13 on 2020-09-28 13:45

from django.db import migrations, models
import django.db.models.deletion
import hipo_django_core.models
import hipo_django_core.utils
import slacker.users.managers
import slacker.users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('slack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigIntegerField(default=hipo_django_core.utils.generate_unique_id, editable=False, primary_key=True, serialize=False)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('username', models.CharField(default=slacker.users.models.generate_string_unique_id, max_length=255, unique=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Only staff users can access Django Admin.')),
                ('slack_user_id', models.CharField(blank=True, max_length=255)),
                ('moku_email', models.EmailField(blank=True, max_length=254)),
                ('moku_password', models.CharField(blank=True, max_length=255)),
                ('moku_api_token', models.CharField(blank=True, max_length=255)),
                ('is_moku_credentials_validated', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('slack_workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='slack.SlackWorkspace')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            bases=(hipo_django_core.models.LogEntryMixin, models.Model),
            managers=[
                ('objects', slacker.users.managers.UserManager()),
            ],
        ),
    ]
