# Generated by Django 2.2.13 on 2020-10-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_slack_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slack_access_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
