# Generated by Django 2.2.13 on 2020-10-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201002_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='moku_status',
            field=models.CharField(blank=True, choices=[('working', 'working'), ('working', 'working'), ('idle', 'idle')], default='idle', max_length=255),
        ),
    ]
