MOKU_STATUS_WORKING = 'working'
MOKU_STATUS_ON_BREAK = 'on_break'
MOKU_STATUS_IDLE = 'idle'

MOKU_STATUS_CHOICES = (
    (MOKU_STATUS_WORKING, MOKU_STATUS_WORKING),
    (MOKU_STATUS_ON_BREAK, MOKU_STATUS_ON_BREAK),
    (MOKU_STATUS_IDLE, MOKU_STATUS_IDLE),
)
